### PR TITLE
fixing wallclock option not working

### PR DESCRIPTION
**Pull request by vincib**
Hi Luca,

I saw that your -w option, which I'm interested in very much, is not working in the current git repository's status.
Please find the small patch to make it work ;) 

Also, I'm building a *wall clock synchronization* option for bmdcapture, allowing to drop or duplicate frames to ensure we have a number of frames corresponding to the capturing computer wallclock (we have cameras sending 62fps instead of 60, and sometime 58~59!... want to "synchronize" that...)

If you are interested, I'll pull request this option too later...

### CODE REVIEW

**Comment by lu-zero** [comment]
Thanks a lot! If I don't merge it today ping me again please (I'm in an
horribly busy week)

**Comment by lu-zero** [comment]
Merged eventually, thanks a lot.

**Comment by vincib** [comment]
Hi,

I made a (somehow big) patch to bmdcapture to allow it to spit out *exactly* the planned number of frames per seconds.

(I have some cameras that spit out between 60 and 62 fps for no reason (maybe the temperature?) instead of 60fps precisely)

This version duplicate or drop frames, ensuring a proper synchronization using clock_gettime() with CLOCK_MONOTONIC option.
(I'm not using gettimeofday for this reason: https://blog.habets.se/2010/09/gettimeofday-should-never-be-used-to-measure-time ) 

Thanks to that, I can use 4 bmdcapture on a 4 input BMD card, and create a realtime mosaic under Linux.

(before that patch, the ffmpeg mosaic would fail quickly since the 4 camera weren't synchronized enough...)

I'm currently testing it heavily on some video capture box.

So, if it work (as of now it seems) 
and if you are interested in this patch, I'll bring it to you as a pull request.

I added the -d option for "drop or duplicate" for this purpose.

**Comment by Badbits** [comment]
If you're using more than one camera you should probably also look into syntonizing them. It's normal for cameras to generate slight variations in fps. What cameras are you using out of interest?

**Pull request closed without merging**
